# Generated by Django 4.2.5 on 2024-08-18 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_alter_students_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='user',
        ),
        migrations.AddField(
            model_name='students',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
