# Generated by Django 4.2.5 on 2024-08-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_students_user_students_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='user',
        ),
    ]
